# Generated by Django 3.2.9 on 2021-12-30 01:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friend_status', models.IntegerField()),
                ('friend_A', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend_A', to=settings.AUTH_USER_MODEL)),
                ('friend_B', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend_B', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('friend_A', 'friend_B')},
            },
        ),
    ]
